# Generated by Django 5.1.4 on 2024-12-29 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('whey', 'Whey'), ('casein', 'Casein'), ('isolate', 'Isolate'), ('mass_gainer', 'Mass Gainer')], default='whey', max_length=20)),
                ('name', models.CharField(max_length=20)),
                ('price', models.IntegerField(default=0)),
                ('description', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='products/images/')),
            ],
        ),
    ]
