# Generated by Django 5.1.4 on 2025-01-22 11:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplementapp', '0002_registermodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='registermodel',
            name='last_login',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
