# Generated by Django 5.1.4 on 2025-02-25 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplementapp', '0006_registermodel_groups_registermodel_is_active_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='مشتری', max_length=100)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
